### ISSUE TITLE
Ça marche pas (t bo Horus)

### ISSUE THREAD

**Issue by remivanboxem** [horus-4ever/python-tetris-YATG#1]
Comme convenu, je t'envoie le traceback du programme :
```py
Traceback (most recent call last):
  File "/home/remi/python-tetris-YATG/main.py", line 7, in <module>
    game.run()
  File "/home/remi/python-tetris-YATG/game/game.py", line 36, in run
    self.board.draw(self.window, (0, 0))
  File "/home/remi/python-tetris-YATG/game/gui_board.py", line 23, in draw
    pygame.draw.rect(surface, Colors.DARK_GREAY, rectangle)
  File "/usr/lib/python3.9/enum.py", line 405, in __getattr__
    raise AttributeError(name) from None
AttributeError: DARK_GREAY
```
Les touches directionnelles ne semblent pas fonctionner également.

**Comment by horus-4ever** [comment]
J'avais oublié de fix la faute de frappe sur "DARK_GREY" :smile: 
Donc ça devrait fonctionner, maintenant.
Quant aux touches directionnelles, il semblerait que ce soit à cause de pygame.
